---
##############################################################################
# Copyright (c) 2017 Huawei Technologies Co.,Ltd and others.
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

- name: upload SPEC CPU2006 ISO
  copy:
    src: /home/opnfv/repos/yardstick/yardstick/resources/cpu2006-1.2.iso
    dest: ~/cpu2006-1.2.iso
  become: true

- name: install SPEC CPU2006
  shell:
    mount -t iso9660 -o ro,exec ~/cpu2006-1.2.iso /mnt;
    cd /mnt;
    ./install.sh -fd /usr/cpu2006;
  args:
      executable: /bin/bash
  become: true
