# Copyright (c) 2017 Intel Corporation.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
- name: fetch fuel master ssh key
  fetch:
    src: /root/.ssh/id_rsa
    dest: /root/.ssh/id_rsa

- name: collect fuel node info
  command: fuel --json node
  register: fuel_node_output

- name: import fuel json
  set_fact:
    fuel_nodes: "{{ fuel_node_output.stdout|from_json }}"

- name: find compute node
  set_fact:
    compute_node: "{{ fuel_nodes|find_fuel_nodes.computes_ips[0] }}"

- name: get remote arch
  command: ssh "{{ compute_node }}" uname -m
  register: uname_output

- set_fact:
    YARD_IMG_ARCH: "{{ 'arm64' if uname_output.stdout.strip() == 'aarch64' else 'amd64' }}"
