---
- name: get nova compute host
  shell:
    source /etc/yardstick/openstack.creds;
    openstack availability zone list --long | grep nova-compute | sort | awk '{print $7}';
  args:
      executable: /bin/bash
  register: compute_nodes

- name: get flavor list
  shell:
    source /etc/yardstick/openstack.creds;
    openstack flavor list | grep "True" | cut -f 2 -d ' ';
  args:
      executable: /bin/bash
  register: flavors

- name: create pinned-cpu and regular aggregate
  shell:
    source /etc/yardstick/openstack.creds;
    openstack aggregate create pinned-cpu;
    openstack aggregate create regular;
    nova aggregate-set-metadata pinned-cpu pinned=true;
    nova aggregate-set-metadata regular pinned=false;
    nova aggregate-add-host pinned-cpu {{ compute_nodes.stdout_lines[0] }};
    nova aggregate-add-host regular {{ compute_nodes.stdout_lines[1] }};
  args:
      executable: /bin/bash

- name: set flavor default property
  shell:
    source /etc/yardstick/openstack.creds;
    openstack flavor set --property aggregate_instance_extra_specs:pinned=false {{item}};
  args:
      executable: /bin/bash
  with_items:
      - '{{ flavors.stdout_lines }}'

- name: create flavor migrate-flavor
  os_nova_flavor:
    cloud: opnfv
    state: present
    name: "{{ flavor }}"
    ram: "{{ ram }}"
    vcpus: "{{ vcpus }}"
    disk: "{{ disk }}"

- name: set property
  shell:
    source /etc/yardstick/openstack.creds;
    openstack flavor set --property hw:cpu_policy=dedicated {{ flavor }};
    openstack flavor set --property aggregate_instance_extra_specs:pinned=true {{ flavor }};
  args:
      executable: /bin/bash
