---
##############################################################################
# Copyright (c) 2017 Huawei Technologies Co.,Ltd and others.
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

- name: set memory reserved for host
  lineinfile:
    dest: /etc/nova/nova.conf
    insertafter: 'DEFAULT'
    line: 'reserved_host_memory_mb={{host_memory}}'

- name: set vcpu pin set
  lineinfile:
    dest: /etc/nova/nova.conf
    insertafter: 'DEFAULT'
    line: 'vcpu_pin_set={{cpu_set}}'
