{
 "title": "Configurable_Dashboard",
 "tags": [
  "yardstick",
  "NSB",
  "BM"
 ],
 "time": { "from": "now/w", "to": "now/w" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "TC_NAME",
    "query": "SHOW TAG VALUES FROM \"metadata_table\" WITH KEY = \"tc_name\""
   },
   {
    "name": "TC_TIME",
    "query": "SHOW TAG VALUES FROM \"metadata_table\" WITH KEY = \"tc_time\" WHERE \"tc_name\"=~ /^$TC_NAME$/"
   },
   {
    "name": "TASK_ID",
    "query": "SELECT \"task_id\" FROM \"metadata_table\" WHERE \"tc_time\"=~ /^$TC_TIME$/"
   }
  ]
 },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "content": "<h5 style=\"font-family:Verdana\"> <a style=\"font: 28px '#31A7D3'\"><center>Test  Parameters</center> </a></h5>\n"
  },
  {
   "title": "Test Precision",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 2, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$TC_NAME$/",
     "select": [
      [
       {
        "params": [
         "tg__0.collect_stats.test_precision"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "task_id", "operator": "=~", "value": "/^$TASK_ID$/" }
     ]
    }
   ]
  },
  {
   "title": "Test Interval",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 7, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$TC_NAME$/",
     "query": "SELECT mean(\"tg__0.collect_stats.duration\") FROM /^$TC_NAME$/ WHERE (\"task_id\" =~ /^$TASK_ID$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "tg__0.collect_stats.duration" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "task_id", "operator": "=~", "value": "/^$TASK_ID$/" }
     ]
    }
   ]
  },
  {
   "title": "Test Duration",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 13, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$TC_NAME$/",
     "select": [
      [
       {
        "params": [
         "tg__0.collect_stats.test_duration"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "task_id", "operator": "=~", "value": "/^$TASK_ID$/" }
     ]
    }
   ]
  },
  {
   "title": "Tolerated Loss",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 20, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$TC_NAME$/",
     "select": [
      [
       {
        "params": [
         "tg__0.collect_stats.tolerated_loss"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "task_id", "operator": "=~", "value": "/^$TASK_ID$/" }
     ]
    }
   ]
  },
  { "title": "Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Cumulative Load Sent by Generator",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 }
  },
  {
   "title": "Cumulative Load Sent by Generator",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "Packets Per Second" }
   ],
   "targets": [
    {
     "alias": "Cumulative Packets Sents",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$TC_NAME$/",
     "select": [
      [
       { "params": [ "vnf__0.packets_fwd" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "task_id", "operator": "=~", "value": "/^$TASK_ID$/" }
     ]
    }
   ]
  },
  { "title": "New row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 18 },
   "content": "<h5 style=\"font-family:Verdana\"> <a style=\"color:#31A7D3\"><a style=\"font: 22px '#31A7D3'\"><center>Throughput</center> </a></h5>\n"
  },
  {
   "title": "Generator Stats: Average Throughout per step",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short", "label": "Million Packets Per Second" }
   ],
   "targets": [
    {
     "alias": "Load Requested to Generator",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$TC_NAME$/",
     "select": [
      [
       {
        "params": [
         "tg__0.collect_stats.RequestedTxThroughput"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "task_id", "operator": "=~", "value": "/^$TASK_ID$/" }
     ]
    },
    {
     "alias": "Load Generated (by the Generator)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$TC_NAME$/",
     "select": [
      [
       {
        "params": [
         "tg__0.collect_stats.TxThroughput"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "task_id", "operator": "=~", "value": "/^$TASK_ID$/" }
     ]
    },
    {
     "alias": "Load Received (by the Generator)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$TC_NAME$/",
     "select": [
      [
       {
        "params": [
         "tg__0.collect_stats.RxThroughput"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "task_id", "operator": "=~", "value": "/^$TASK_ID$/" }
     ]
    }
   ]
  },
  {
   "title": "Packet size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "none", "label": "Packet Size (Bytes)" }
   ],
   "targets": [
    {
     "alias": "Packet Size",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$TC_NAME$/",
     "select": [
      [
       { "params": [ "tg__0.collect_stats.PktSize" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "task_id", "operator": "=~", "value": "/^$TASK_ID$/" }
     ]
    }
   ]
  },
  { "title": "New row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "SUT Stats - Load Received By SUT",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short", "label": "Million Packets per Second" }
   ],
   "targets": [
    {
     "alias": "SUT Packets Received: Prox",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "/^$TC_NAME$/",
     "select": [
      [
       { "params": [ "vnf__0.curr_packets_in" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 1000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "task_id", "operator": "=~", "value": "/^$TASK_ID$/" }
     ]
    },
    {
     "alias": "SUT Packets Received",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$TC_NAME$/",
     "select": [
      [
       { "params": [ "vnf__0.packets_in" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "task_id", "operator": "=~", "value": "/^$TASK_ID$/" }
     ]
    }
   ]
  },
  {
   "title": "SUT Stats - Load Forwarded By SUT",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "short", "label": "Million Packets per Second" }
   ],
   "targets": [
    {
     "alias": "SUT Packets Sent: Prox",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$TC_NAME$/",
     "select": [
      [
       { "params": [ "vnf__0.curr_packets_fwd" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 1000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "task_id", "operator": "=~", "value": "/^$TASK_ID$/" }
     ]
    },
    {
     "alias": "SUT Packets Sent",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$TC_NAME$/",
     "select": [
      [
       { "params": [ "vnf__0.packets_fwd" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "task_id", "operator": "=~", "value": "/^$TASK_ID$/" }
     ]
    }
   ]
  },
  {
   "title": "Packets Sent by Generator per second and per interface",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short", "label": "Million Packets  Per Second" }
   ],
   "targets": [
    {
     "alias": "TG xe-0 Out packets",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$TC_NAME$/",
     "query": "SELECT mean(\"tg__0.collect_stats.live_stats.xe0.out_packets\")  / 1000000 FROM \"tc_prox_baremetal_l3fwd-4\" WHERE $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       {
        "params": [
         "tg__0.collect_stats.live_stats.xe0.out_packets"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 1000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "task_id", "operator": "=~", "value": "/^$TASK_ID$/" }
     ]
    },
    {
     "alias": "TG xe-1 Out packets",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$TC_NAME$/",
     "query": "SELECT mean(\"tg__0.collect_stats.live_stats.xe1.out_packets\") FROM \"tc_prox_baremetal_l3fwd-4\" WHERE $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       {
        "params": [
         "tg__0.collect_stats.live_stats.xe1.out_packets"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 1000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "task_id", "operator": "=~", "value": "/^$TASK_ID$/" }
     ]
    },
    {
     "alias": "TG xe-2 Out packets",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$TC_NAME$/",
     "query": "SELECT mean(\"tg__0.collect_stats.xe2.out_packets\")  / 1000000 FROM \"tc_prox_baremetal_l3fwd-4\" WHERE $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       {
        "params": [
         "tg__0.collect_stats.live_stats.xe2.out_packets"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 1000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "task_id", "operator": "=~", "value": "/^$TASK_ID$/" }
     ]
    },
    {
     "alias": "TG xe-3 Out packets",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$TC_NAME$/",
     "query": "SELECT mean(\"tg__0.collect_stats.xe3.out_packets\")  / 1000000 FROM \"tc_prox_baremetal_l3fwd-4\" WHERE $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       {
        "params": [
         "tg__0.collect_stats.live_stats.xe3.out_packets"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 1000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "task_id", "operator": "=~", "value": "/^$TASK_ID$/" }
     ]
    }
   ]
  },
  {
   "title": "Packets Received by Generator per second and per interface",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "short", "label": "Million Packets Per Second" }
   ],
   "targets": [
    {
     "alias": "TG xe-0 in packets",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$TC_NAME$/",
     "query": "SELECT mean(\"tg__0.collect_stats.xe0.in_packets\")  / 1000000 FROM \"tc_prox_baremetal_l3fwd-4\" WHERE $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       {
        "params": [
         "tg__0.collect_stats.live_stats.xe0.in_packets"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 1000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "task_id", "operator": "=~", "value": "/^$TASK_ID$/" }
     ]
    },
    {
     "alias": "TG xe-1 in packets",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$TC_NAME$/",
     "query": "SELECT mean(\"tg__0.collect_stats.live_stats.xe1.in_packets\") FROM \"tc_prox_baremetal_l3fwd-4\" WHERE $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       {
        "params": [
         "tg__0.collect_stats.live_stats.xe1.in_packets"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 1000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "task_id", "operator": "=~", "value": "/^$TASK_ID$/" }
     ]
    },
    {
     "alias": "TG xe-2 in packets",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$TC_NAME$/",
     "query": "SELECT mean(\"tg__0.collect_stats.live_stats.xe2.in_packets\") FROM \"tc_prox_baremetal_l3fwd-4\" WHERE $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       {
        "params": [
         "tg__0.collect_stats.live_stats.xe2.in_packets"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 1000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "task_id", "operator": "=~", "value": "/^$TASK_ID$/" }
     ]
    },
    {
     "alias": "TG xe-3 in packets",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$TC_NAME$/",
     "query": "SELECT mean(\"tg__0.collect_stats.live_stats.xe3.in_packets\") FROM \"tc_prox_baremetal_l3fwd-4\" WHERE $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       {
        "params": [
         "tg__0.collect_stats.live_stats.xe3.in_packets"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 1000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "task_id", "operator": "=~", "value": "/^$TASK_ID$/" }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 46 },
   "content": "<h5 style=\"font-family:Verdana\"> <a style=\"color:#31A7D3\"><a style=\"font: 22px '#31A7D3'\"><center>Generator Stats: Packets per Step</center> </a></h5>\n"
  },
  {
   "title": "Packets Sent by Generator per Step",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short", "label": "Million Packets  Per Step" }
   ],
   "targets": [
    {
     "alias": "TG xe-0 Out packets",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tc_prox_baremetal_l3fwd-4",
     "query": "SELECT mean(\"tg__0.collect_stats.xe0.out_packets\") FROM \"tc_prox_baremetal_l3fwd-4\" WHERE $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       {
        "params": [
         "tg__0.collect_stats.xe0.out_packets"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 1000000" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "TG xe-1 Out packets",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tc_prox_baremetal_l3fwd-4",
     "query": "SELECT mean(\"tg__0.collect_stats.xe1.out_packets\") FROM \"tc_prox_baremetal_l3fwd-4\" WHERE $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       {
        "params": [
         "tg__0.collect_stats.xe1.out_packets"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 1000000" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "TG xe-2 Out packets",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tc_prox_baremetal_l3fwd-4",
     "query": "SELECT mean(\"tg__0.collect_stats.xe2.out_packets\") FROM \"tc_prox_baremetal_l3fwd-4\" WHERE $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       {
        "params": [
         "tg__0.collect_stats.xe2.out_packets"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 1000000" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "TG xe-3 Out packets",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tc_prox_baremetal_l3fwd-4",
     "query": "SELECT mean(\"tg__0.collect_stats.xe3.out_packets\") FROM \"tc_prox_baremetal_l3fwd-4\" WHERE $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       {
        "params": [
         "tg__0.collect_stats.xe3.out_packets"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 1000000" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Packets Received by Generator per Step",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "short", "label": "Million Packets Per Step" }
   ],
   "targets": [
    {
     "alias": "TG xe-0 in packets",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tc_prox_baremetal_l3fwd-4",
     "query": "SELECT mean(\"tg__0.collect_stats.xe0.in_packets\") FROM \"tc_prox_baremetal_l3fwd-4\" WHERE $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       {
        "params": [
         "tg__0.collect_stats.xe0.in_packets"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 1000000" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "TG xe-1 in packets",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tc_prox_baremetal_l3fwd-4",
     "query": "SELECT mean(\"tg__0.collect_stats.xe1.in_packets\") FROM \"tc_prox_baremetal_l3fwd-4\" WHERE $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       {
        "params": [
         "tg__0.collect_stats.xe1.in_packets"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 1000000" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "TG xe-2 in packets",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tc_prox_baremetal_l3fwd-4",
     "query": "SELECT mean(\"tg__0.collect_stats.xe2.in_packets\") FROM \"tc_prox_baremetal_l3fwd-4\" WHERE $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       {
        "params": [
         "tg__0.collect_stats.xe2.in_packets"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 1000000" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "TG xe-3 in packets",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tc_prox_baremetal_l3fwd-4",
     "query": "SELECT mean(\"tg__0.collect_stats.xe3.in_packets\") FROM \"tc_prox_baremetal_l3fwd-4\" WHERE $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       {
        "params": [
         "tg__0.collect_stats.xe3.in_packets"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 1000000" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  { "title": "New row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "SUCCESS CRITERIA: TX Total  = Rx Total + Tolerated Loss",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "short", "label": "Packets Per Second" }
   ],
   "targets": [
    {
     "alias": "SUCCESS Tx Total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/^$TC_NAME$/",
     "query": "SELECT \"tg__0.collect_stats.tx_total\" FROM \"tc_prox_baremetal_l3fwd-4\" WHERE \"tg__0.collect_stats.tx_total\" = 'Success' AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "tg__0.collect_stats.tx_total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "tg__0.collect_stats.Status", "operator": "=", "value": "Success" },
      { "condition": "AND", "key": "task_id", "operator": "=~", "value": "/^$TASK_ID$/" }
     ]
    },
    {
     "alias": "SUCCESS Rx Total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$TC_NAME$/",
     "select": [
      [
       { "params": [ "tg__0.collect_stats.rx_total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "tg__0.collect_stats.Status", "operator": "=", "value": "Success" },
      { "condition": "AND", "key": "task_id", "operator": "=~", "value": "/^$TASK_ID$/" }
     ]
    },
    {
     "alias": "SUCCESS ALLOWABLE LOST PACKETS",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$TC_NAME$/",
     "select": [
      [
       {
        "params": [
         "tg__0.collect_stats.can_be_lost"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "tg__0.collect_stats.Status", "operator": "=", "value": "Success" },
      { "condition": "AND", "key": "task_id", "operator": "=~", "value": "/^$TASK_ID$/" }
     ]
    },
    {
     "alias": "Current Drop Percentage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$TC_NAME$/",
     "select": [
      [
       {
        "params": [
         "tg__0.collect_stats.CurrentDropPercentage"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "task_id", "operator": "=~", "value": "/^$TASK_ID$/" }
     ]
    },
    {
     "alias": "Drop Percentage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$TC_NAME$/",
     "select": [
      [
       {
        "params": [
         "tg__0.collect_stats.DropPercentage"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "task_id", "operator": "=~", "value": "/^$TASK_ID$/" }
     ]
    }
   ]
  },
  {
   "title": "Line Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "yaxes": [
    { "format": "percent", "label": "Percentage of Line Rate" }
   ],
   "targets": [
    {
     "alias": "MAX Line Rate",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "/^$TC_NAME$/",
     "query": "SELECT \"tg__0.collect_stats.tx_total\" FROM \"tc_prox_baremetal_l3fwd-4\" WHERE \"tg__0.collect_stats.tx_total\" = 'Success' AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "tg__0.collect_stats.MAX_Rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "task_id", "operator": "=~", "value": "/^$TASK_ID$/" }
     ]
    },
    {
     "alias": "MIN Line Rate",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "/^$TC_NAME$/",
     "select": [
      [
       { "params": [ "tg__0.collect_stats.MIN_Rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "task_id", "operator": "=~", "value": "/^$TASK_ID$/" }
     ]
    },
    {
     "alias": "Current Line Rate_Prox",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "/^$TC_NAME$/",
     "select": [
      [
       { "params": [ "tg__0.collect_stats.Test_Rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "task_id", "operator": "=~", "value": "/^$TASK_ID$/" }
     ]
    },
    {
     "alias": "Current Line Rate",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$TC_NAME$/",
     "select": [
      [
       { "params": [ "tg__0.collect_stats.Rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "task_id", "operator": "=~", "value": "/^$TASK_ID$/" }
     ]
    }
   ]
  },
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 67 },
   "content": "<h5 style=\"font-family:Verdana\"> <a style=\"color:#31A7D3\"><a style=\"font: 22px '#31A7D3'\"><center>Latency</center> </a></h5>"
  },
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 } },
  {
   "title": "xe0 Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 71 },
   "yaxes": [
    { "format": "short", "label": "usec" }
   ],
   "targets": [
    {
     "alias": "xe0 Latency Avg",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "tc_prox_baremetal_l3fwd-4",
     "select": [
      [
       {
        "params": [
         "tg__0.collect_stats.LatencyAvg.5"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "xe0 Latency Max",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tc_prox_baremetal_l3fwd-4",
     "select": [
      [
       {
        "params": [
         "tg__0.collect_stats.LatencyMax.5"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "xe1 Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 71 },
   "yaxes": [
    { "format": "short", "label": "usec" }
   ],
   "targets": [
    {
     "alias": "xe1 Latency Avg",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "tc_prox_baremetal_l3fwd-4",
     "select": [
      [
       {
        "params": [
         "tg__0.collect_stats.LatencyAvg.6"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "xe1 Latency Max",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tc_prox_baremetal_l3fwd-4",
     "select": [
      [
       {
        "params": [
         "tg__0.collect_stats.LatencyMax.6"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "xe2 Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 79 },
   "yaxes": [
    { "format": "short", "label": "usec" }
   ],
   "targets": [
    {
     "alias": "xe2 Latency Avg",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "tc_prox_baremetal_l3fwd-4",
     "select": [
      [
       {
        "params": [
         "tg__0.collect_stats.LatencyAvg.7"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "xe2 Latency Max",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tc_prox_baremetal_l3fwd-4",
     "select": [
      [
       {
        "params": [
         "tg__0.collect_stats.LatencyMax.7"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "xe3 Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 79 },
   "yaxes": [
    { "format": "short", "label": "usec" }
   ],
   "targets": [
    {
     "alias": "xe3 Latency Avg",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "tc_prox_baremetal_l3fwd-4",
     "select": [
      [
       {
        "params": [
         "tg__0.collect_stats.LatencyAvg.8"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "xe3 Latency Max",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tc_prox_baremetal_l3fwd-4",
     "select": [
      [
       {
        "params": [
         "tg__0.collect_stats.LatencyMax.8"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 87 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 88 },
   "content": "<h5 style=\"font-family:Verdana\"> <a style=\"color:#31A7D3\"><a style=\"font: 22px '#31A7D3'\"><center>CPU Utilization</center> </a></h5>"
  },
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 91 } },
  {
   "title": "Traffic Generator CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 92 },
   "yaxes": [
    { "format": "short", "label": "% Utilization" }
   ],
   "targets": [
    {
     "alias": "CPU 0 Utilization",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/^$TC_NAME$/",
     "select": [
      [
       {
        "params": [
         "tg_0.yardstick.core.cpu.0.percent-user"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "task_id", "operator": "=~", "value": "/^$TASK_ID$/" }
     ]
    },
    {
     "alias": "CPU 1 Utilization - Gen XE0",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$TC_NAME$/",
     "select": [
      [
       {
        "params": [
         "tg_0.yardstick.core.cpu.1.percent-user"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "task_id", "operator": "=~", "value": "/^$TASK_ID$/" }
     ]
    },
    {
     "alias": "CPU 2 Utilization - Gen XE1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$TC_NAME$/",
     "select": [
      [
       {
        "params": [
         "tg_0.yardstick.core.cpu.2.percent-user"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "task_id", "operator": "=~", "value": "/^$TASK_ID$/" }
     ]
    },
    {
     "alias": "CPU 3 Utilization - Gen  XE2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$TC_NAME$/",
     "select": [
      [
       {
        "params": [
         "tg_0.yardstick.core.cpu.3.percent-user"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "task_id", "operator": "=~", "value": "/^$TASK_ID$/" }
     ]
    },
    {
     "alias": "CPU 4 Utilization - Gen  XE3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$TC_NAME$/",
     "select": [
      [
       {
        "params": [
         "tg_0.yardstick.core.cpu.4.percent-user"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "task_id", "operator": "=~", "value": "/^$TASK_ID$/" }
     ]
    },
    {
     "alias": "CPU 5 Utilization - Latency XE0",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$TC_NAME$/",
     "select": [
      [
       {
        "params": [
         "tg_0.yardstick.core.cpu.5.percent-user"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "task_id", "operator": "=~", "value": "/^$TASK_ID$/" }
     ]
    },
    {
     "alias": "CPU 6 Utilization - Latency XE1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$TC_NAME$/",
     "select": [
      [
       {
        "params": [
         "tg_0.yardstick.core.cpu.6.percent-user"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "task_id", "operator": "=~", "value": "/^$TASK_ID$/" }
     ]
    },
    {
     "alias": "CPU 7 Utilization - Latency XE2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$TC_NAME$/",
     "select": [
      [
       {
        "params": [
         "tg_0.yardstick.core.cpu.7.percent-user"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "task_id", "operator": "=~", "value": "/^$TASK_ID$/" }
     ]
    },
    {
     "alias": "CPU 8 Utilization - Latency XE3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$TC_NAME$/",
     "select": [
      [
       {
        "params": [
         "tg_0.yardstick.core.cpu.8.percent-user"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "task_id", "operator": "=~", "value": "/^$TASK_ID$/" }
     ]
    },
    {
     "alias": "CPU 8 Utilization - Idle",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$TC_NAME$/",
     "select": [
      [
       {
        "params": [
         "tg_0.yardstick.core.cpu.9.percent-user"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "task_id", "operator": "=~", "value": "/^$TASK_ID$/" }
     ]
    }
   ]
  },
  {
   "title": "VNF CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 92 },
   "yaxes": [
    { "format": "short", "label": "% Utilization" }
   ],
   "targets": [
    {
     "alias": "CPU 0 Utilization",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/^$TC_NAME$/",
     "select": [
      [
       {
        "params": [
         "vnf_0.yardstick.core.cpu.0.percent-user"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "task_id", "operator": "=~", "value": "/^$TASK_ID$/" }
     ]
    },
    {
     "alias": "CPU 1 Utilization - RX XE0 - Routing XE0 and XE1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/^$TC_NAME$/",
     "select": [
      [
       {
        "params": [
         "vnf_0.yardstick.core.cpu.1.percent-user"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "task_id", "operator": "=~", "value": "/^$TASK_ID$/" }
     ]
    },
    {
     "alias": "CPU 2 Utilization - RX XE1 - Routing XE0 and XE1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/^$TC_NAME$/",
     "select": [
      [
       {
        "params": [
         "vnf_0.yardstick.core.cpu.2.percent-user"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "task_id", "operator": "=~", "value": "/^$TASK_ID$/" }
     ]
    },
    {
     "alias": "CPU 3 Utilization - RX XE2 - Routing XE2 and XE3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/^$TC_NAME$/",
     "select": [
      [
       {
        "params": [
         "vnf_0.yardstick.core.cpu.3.percent-user"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "task_id", "operator": "=~", "value": "/^$TASK_ID$/" }
     ]
    },
    {
     "alias": "CPU 4 Utilization - RX XE3 - Routing XE2 and XE3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/^$TC_NAME$/",
     "select": [
      [
       {
        "params": [
         "vnf_0.yardstick.core.cpu.4.percent-user"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "task_id", "operator": "=~", "value": "/^$TASK_ID$/" }
     ]
    },
    {
     "alias": "CPU 5 Utilization - Idle",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/^$TC_NAME$/",
     "select": [
      [
       {
        "params": [
         "vnf_0.yardstick.core.cpu.5.percent-user"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "task_id", "operator": "=~", "value": "/^$TASK_ID$/" }
     ]
    },
    {
     "alias": "CPU 6 Utilization - Idle",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/^$TC_NAME$/",
     "select": [
      [
       {
        "params": [
         "vnf_0.yardstick.core.cpu.6.percent-user"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "task_id", "operator": "=~", "value": "/^$TASK_ID$/" }
     ]
    },
    {
     "alias": "CPU 7 Utilization - Idle",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/^$TC_NAME$/",
     "select": [
      [
       {
        "params": [
         "vnf_0.yardstick.core.cpu.7.percent-user"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "task_id", "operator": "=~", "value": "/^$TASK_ID$/" }
     ]
    },
    {
     "alias": "CPU 8 Utilization - Idle",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/^$TC_NAME$/",
     "select": [
      [
       {
        "params": [
         "vnf_0.yardstick.core.cpu.8.percent-user"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "task_id", "operator": "=~", "value": "/^$TASK_ID$/" }
     ]
    }
   ]
  }
 ]
}