{
 "title": "Upstream Processing (Per Service Group)",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Scenario_One",
    "query": "SHOW TAG Values with key =\"host\""
   },
   {
    "name": "Scenario_Two",
    "query": "SHOW TAG Values with key =\"host\""
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 0 },
   "content": "<h1 align = \"center\">$Scenario_One</h1>"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 0 },
   "content": "<h1 align = \"center\">$Scenario_Two</h1>"
  },
  {
   "title": "L2TP Frame RX Bitrate",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_rx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "/1000000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "bits_per_second" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" }
     ]
    }
   ]
  },
  {
   "title": "RX L2TP Frames",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_rx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "/1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "packets_per_second" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" }
     ]
    }
   ]
  },
  {
   "title": "TX Bitrate",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_tx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "/1000000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "bits_per_second" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" }
     ]
    }
   ]
  },
  {
   "title": "TX Packets",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_tx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "/1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "packets_per_second" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" }
     ]
    }
   ]
  },
  {
   "title": "RX Bitrate",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_rx",
     "query": "SELECT distinct(\"value\") /1000000000 FROM \"upstream_rx\" WHERE (\"type\" = 'bits_per_second' AND \"type_instance\" = 'rx') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "/1000000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "bits_per_second" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Scenario_Two$/" }
     ]
    }
   ]
  },
  {
   "title": "RX L2TP Frames",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_rx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "/1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "packets_per_second" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Scenario_Two$/" }
     ]
    }
   ]
  },
  {
   "title": "L2TP  Frame TX Bitrate",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_tx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "/1000000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "bits_per_second" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Scenario_Two$/" }
     ]
    }
   ]
  },
  {
   "title": "TX Packets",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_tx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "/1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "packets_per_second" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Scenario_Two$/" }
     ]
    }
   ]
  },
  {
   "title": "Avg RX Frame Size",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_rx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "average_frame_size_per_second" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" }
     ]
    }
   ]
  },
  {
   "title": "Avg TX Packet Size",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_tx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "average_frame_size_per_second" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" }
     ]
    }
   ]
  },
  {
   "title": "Avg RX Frame Size",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_rx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "average_frame_size_per_second" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Scenario_Two$/" }
     ]
    }
   ]
  },
  {
   "title": "Avg TX Packet Size",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_tx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "average_frame_size_per_second" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Scenario_Two$/" }
     ]
    }
   ]
  },
  {
   "title": "RX Dropped",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_rx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "/1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "dropped_per_second" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" }
     ]
    }
   ]
  },
  {
   "title": "TX Dropped",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_tx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "/1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "dropped_per_second" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" }
     ]
    }
   ]
  },
  {
   "title": "RX Dropped",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_rx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "/1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "dropped_per_second" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Scenario_Two$/" }
     ]
    }
   ]
  },
  {
   "title": "TX Dropped",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_tx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "/1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "dropped_per_second" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Scenario_Two$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU Cycles per Packet Cycle",
   "type": "graph",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "# Cycles" }
   ],
   "targets": [
    {
     "alias": "TX",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "upstream_tx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "upstream_cycles" }
     ]
    },
    {
     "alias": "Ethernet CRC Check",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "upstream_eth_crc_check",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "upstream_cycles" }
     ]
    },
    {
     "alias": "Decryption",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "upstream_decryption",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "upstream_cycles" }
     ]
    },
    {
     "alias": "DOCSIS Frame Extraction",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "upstream_docsis_frame_extraction",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "upstream_cycles" }
     ]
    },
    {
     "alias": "DOCSIS Segment Reassembly",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "upstream_docsis_segment_reassembly",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "upstream_cycles" }
     ]
    },
    {
     "alias": "UEPI Decap",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "upstream_uepi_decap",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "upstream_cycles" }
     ]
    },
    {
     "alias": "UEPI Verification",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "upstream_uepi_verification",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "upstream_cycles" }
     ]
    },
    {
     "alias": "RX",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "upstream_rx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "upstream_cycles" }
     ]
    }
   ]
  },
  {
   "title": "RX Dequeue per Second",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 8 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "Non-Empty",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_pkts_present",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "rx_dequeue_per_second" }
     ]
    },
    {
     "alias": "Empty",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_pkts_not_present",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "rx_dequeue_per_second" }
     ]
    }
   ]
  },
  {
   "title": "CPU Cycles per Packet Cycle",
   "type": "graph",
   "gridPos": { "h": 11, "w": 6, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "# Cycles" }
   ],
   "targets": [
    {
     "alias": "TX",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "upstream_tx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_Two$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "upstream_cycles" }
     ]
    },
    {
     "alias": "Ethernet CRC Check",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "upstream_eth_crc_check",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_Two$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "upstream_cycles" }
     ]
    },
    {
     "alias": "Decryption",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "upstream_decryption",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_Two$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "upstream_cycles" }
     ]
    },
    {
     "alias": "DOCSIS Frame Extraction",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "upstream_docsis_frame_extraction",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_Two$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "upstream_cycles" }
     ]
    },
    {
     "alias": "DOCSIS Segment Reassembly",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "upstream_docsis_segment_reassembly",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_Two$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "upstream_cycles" }
     ]
    },
    {
     "alias": "UEPI Decap",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "upstream_uepi_decap",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_Two$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "upstream_cycles" }
     ]
    },
    {
     "alias": "UEPI Verification",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "upstream_uepi_verification",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_Two$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "upstream_cycles" }
     ]
    },
    {
     "alias": "RX",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "upstream_rx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_Two$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "upstream_cycles" }
     ]
    }
   ]
  },
  {
   "title": "RX Dequeue per Second",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 8 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "Non-Empty",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_pkts_present",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_Two$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "rx_dequeue_per_second" }
     ]
    },
    {
     "alias": "Empty",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_pkts_not_present",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_Two$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "rx_dequeue_per_second" }
     ]
    }
   ]
  },
  {
   "title": "Scheduled Yields Per Second",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_sched",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "yields_per_second" }
     ]
    }
   ]
  },
  {
   "title": "Scheduled Yields Per Second",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_sched",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_Two$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "yields_per_second" }
     ]
    }
   ]
  },
  {
   "title": "Sleeping Yields Per Second",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 17 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_sleep",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" }
     ]
    }
   ]
  },
  {
   "title": "Sleeping Yields Per Second",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 17 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_sleep",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_Two$/" }
     ]
    }
   ]
  },
  {
   "title": "CM Lookup",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 19 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "Matched",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_matched",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "cm_lookup" }
     ]
    },
    {
     "alias": "Unmatched",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_unmatched",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "cm_lookup" }
     ]
    }
   ]
  },
  {
   "title": "# Packets per CM Lookup",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 19 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "packets_per_cm_lookup" }
     ]
    }
   ]
  },
  {
   "title": "CM Lookup",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 19 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "Matched",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_matched",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_Two$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "cm_lookup" }
     ]
    },
    {
     "alias": "Unmatched",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_unmatched",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_Two$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "cm_lookup" }
     ]
    }
   ]
  },
  {
   "title": "# Packets per CM Lookup",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 19 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_Two$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "packets_per_cm_lookup" }
     ]
    }
   ]
  },
  {
   "title": "Active CMs per Second",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 22 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "active_cms_per_second" }
     ]
    }
   ]
  },
  {
   "title": "Active CMs per Second",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 22 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_Two$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "active_cms_per_second" }
     ]
    }
   ]
  },
  {
   "title": "IP Address per CM",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 25 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "ip_addr_per_cm" }
     ]
    }
   ]
  },
  {
   "title": "IP Address per CM",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 25 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_Two$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "ip_addr_per_cm" }
     ]
    }
   ]
  },
  {
   "title": "L2TP Verify",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 28 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "Valid",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_valid",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "l2tp_verify" }
     ]
    },
    {
     "alias": "Invalid",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_invalid",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "l2tp_verify" }
     ]
    }
   ]
  },
  {
   "title": "UEPI Frames",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 28 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "Full",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_full",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "uepi_frames" }
     ]
    },
    {
     "alias": "Partial",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_partial",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "uepi_frames" }
     ]
    }
   ]
  },
  {
   "title": "L2TP Verify",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 28 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "Valid",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_valid",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_Two$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "l2tp_verify" }
     ]
    },
    {
     "alias": "Invalid",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_invalid",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_Two$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "l2tp_verify" }
     ]
    }
   ]
  },
  {
   "title": "UEPI Frames",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 28 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "Full",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_full",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "uepi_frames" }
     ]
    },
    {
     "alias": "Partial",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_partial",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "uepi_frames" }
     ]
    }
   ]
  },
  {
   "title": "UEPI Drops per Second",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 36 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "uepi_drops_per_second" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" }
     ]
    }
   ]
  },
  {
   "title": "UEPI Frames per Second",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 36 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "uepi_frames_per_second" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" }
     ]
    }
   ]
  },
  {
   "title": "UEPI Drops per Second",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 36 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "uepi_drops_per_second" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Scenario_Two$/" }
     ]
    }
   ]
  },
  {
   "title": "UEPI Frames per Second",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 36 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "uepi_frames_per_second" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Scenario_Two$/" }
     ]
    }
   ]
  },
  {
   "title": "UEPI Frame Type",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "OFDMA",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_ofdma",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "uepi_frame_type" }
     ]
    },
    {
     "alias": "SC QAM",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_sc_qam",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "uepi_frame_type" }
     ]
    }
   ]
  },
  {
   "title": "Content Per Uepi",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 38 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "data",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_psp_data",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "content_per_uepi" }
     ]
    },
    {
     "alias": "header",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_psp_header",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "content_per_uepi" }
     ]
    },
    {
     "alias": "trailer",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_psp_trailer",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "content_per_uepi" }
     ]
    },
    {
     "alias": "other",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_other",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "content_per_uepi" }
     ]
    }
   ]
  },
  {
   "title": "UEPI Frame Type",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "OFDMA",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_ofdma",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_Two$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "uepi_frame_type" }
     ]
    },
    {
     "alias": "SC QAM",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_sc_qam",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_Two$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "uepi_frame_type" }
     ]
    }
   ]
  },
  {
   "title": "Content Per Uepi",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 38 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "data",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_psp_data",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_Two$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "content_per_uepi" }
     ]
    },
    {
     "alias": "header",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_psp_header",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_Two$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "content_per_uepi" }
     ]
    },
    {
     "alias": "trailer",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_psp_trailer",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_Two$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "content_per_uepi" }
     ]
    },
    {
     "alias": "other",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_other",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_Two$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "content_per_uepi" }
     ]
    }
   ]
  },
  {
   "title": "DOCSIS Reasembly",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 47 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "Success",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_success",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "docsis_reassembly" }
     ]
    },
    {
     "alias": "Fail",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_fail",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "docsis_reassembly" }
     ]
    }
   ]
  },
  {
   "title": "HCS Verify",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 47 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "Success",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_success",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "hcs_verify" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" }
     ]
    },
    {
     "alias": "Fail",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_fail",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "hcs_verify" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" }
     ]
    }
   ]
  },
  {
   "title": "DOCSIS Reasembly",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 47 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "Success",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_success",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_Two$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "docsis_reassembly" }
     ]
    },
    {
     "alias": "Fail",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_fail",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_Two$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "docsis_reassembly" }
     ]
    }
   ]
  },
  {
   "title": "HCS Verify",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 47 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "Success",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_success",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "hcs_verify" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Scenario_Two$/" }
     ]
    },
    {
     "alias": "Fail",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_fail",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "hcs_verify" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Scenario_Two$/" }
     ]
    }
   ]
  },
  {
   "title": "DOCSIS Frames per UEPI",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 55 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "docsis_frames_per_uepi" }
     ]
    }
   ]
  },
  {
   "title": "DOCSIS Frames per Segment",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 55 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "docsis_frames_per_segment" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" }
     ]
    }
   ]
  },
  {
   "title": "DOCSIS Frames per UEPI",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 55 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_Two$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "docsis_frames_per_uepi" }
     ]
    }
   ]
  },
  {
   "title": "DOCSIS Frames per Segment",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 55 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "docsis_frames_per_segment" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Scenario_Two$/" }
     ]
    }
   ]
  },
  {
   "title": "DOCSIS Frames per Second",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 57 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "docsis_frames_per_second" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" }
     ]
    }
   ]
  },
  {
   "title": "Average DOCSIS Segment Length",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 57 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "average_docsis_segment_length" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" }
     ]
    }
   ]
  },
  {
   "title": "DOCSIS Frames per Second",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 57 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "docsis_frames_per_second" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Scenario_Two$/" }
     ]
    }
   ]
  },
  {
   "title": "Average DOCSIS Segment Length",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 57 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "average_docsis_segment_length" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Scenario_Two$/" }
     ]
    }
   ]
  },
  {
   "title": "Crypto Acceleration",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 59 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "AESNI",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_aesni",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "crypto_accel" }
     ]
    },
    {
     "alias": "QAT",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_qat",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "crypto_accel" }
     ]
    },
    {
     "alias": "None",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_none",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "crypto_accel" }
     ]
    }
   ]
  },
  {
   "title": "Crypto Algo",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 59 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "AES",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_aes",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "crypto_algo" }
     ]
    },
    {
     "alias": "DES",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_des",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "crypto_algo" }
     ]
    },
    {
     "alias": "None",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_none",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "crypto_algo" }
     ]
    }
   ]
  },
  {
   "title": "CRC Verify",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 59 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "Success",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_success",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "crc_verify" }
     ]
    },
    {
     "alias": "Fail",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_fail",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_One$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "crc_verify" }
     ]
    }
   ]
  },
  {
   "title": "Crypto Acceleration",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 59 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "AESNI",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_aesni",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_Two$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "crypto_accel" }
     ]
    },
    {
     "alias": "QAT",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_qat",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_Two$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "crypto_accel" }
     ]
    },
    {
     "alias": "None",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_none",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_Two$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "crypto_accel" }
     ]
    }
   ]
  },
  {
   "title": "Crypto Algo",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 59 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "AES",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_aes",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_Two$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "crypto_algo" }
     ]
    },
    {
     "alias": "DES",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_des",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_Two$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "crypto_algo" }
     ]
    },
    {
     "alias": "None",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_none",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_Two$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "crypto_algo" }
     ]
    }
   ]
  },
  {
   "title": "CRC Verify",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 59 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "Success",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_success",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_Two$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "crc_verify" }
     ]
    },
    {
     "alias": "Fail",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_fail",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Scenario_Two$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "crc_verify" }
     ]
    }
   ]
  }
 ]
}