{
 "title": "Power Consumption",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "CPU_1",
    "query": "show tag values with key = \"type_instance\""
   },
   {
    "name": "CPU_2",
    "query": "show tag values with key = \"type_instance\""
   }
  ]
 },
 "panels": [
  {
   "title": "Wall Power",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "alias": "Watts",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "ipmi_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      {
       "key": "type_instance",
       "operator": "=",
       "value": "PS1 Input Power power_supply (10.1)"
      },
      { "condition": "AND", "key": "type", "operator": "=", "value": "power" }
     ]
    },
    {
     "alias": "Downstream",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"last\") / 1000000000\nFROM\n(\nSELECT last(\"value\") \nFROM \"autogen\".\"downstream_rx\" \nWHERE ( \"type\" = 'bits_per_second') \nGROUP BY host\n)\nGROUP BY time(10s) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Upstream",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"last\") / 1000000000\nFROM\n(\nSELECT last(\"value\") \nFROM \"autogen\".\"upstream_tx\" \nWHERE ( \"type\" = 'bits_per_second') \nGROUP BY host\n)\nGROUP BY time(10s) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU Socket Power Consumption",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "alias": "Watts - Pkg 0",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "turbostat_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "pkg00" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "power" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "pkg" }
     ]
    },
    {
     "alias": "Watts - Pkg 1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "turbostat_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "pkg01" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "power" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "pkg" }
     ]
    }
   ]
  },
  {
   "title": "DRAM Power Consumption",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "alias": "package 0",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "turbostat_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "pkg00" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "power" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "DRAM" }
     ]
    },
    {
     "alias": "package 1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "turbostat_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "pkg01" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "power" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "DRAM" }
     ]
    }
   ]
  },
  {
   "title": "Frequency per Core",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "hertz", "label": "Frequency" }
   ],
   "targets": [
    {
     "alias": "0",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpufreq_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "localhost" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "cpufreq" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "0" }
     ]
    },
    {
     "alias": "1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpufreq_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "localhost" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "cpufreq" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "1" }
     ]
    },
    {
     "alias": "2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpufreq_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "localhost" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "cpufreq" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "2" }
     ]
    },
    {
     "alias": "3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpufreq_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "localhost" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "cpufreq" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "3" }
     ]
    },
    {
     "alias": "4",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpufreq_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "localhost" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "cpufreq" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "4" }
     ]
    },
    {
     "alias": "5",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpufreq_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "localhost" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "cpufreq" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "5" }
     ]
    },
    {
     "alias": "6",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpufreq_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "localhost" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "cpufreq" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "6" }
     ]
    },
    {
     "alias": "7",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpufreq_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "localhost" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "cpufreq" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "7" }
     ]
    },
    {
     "alias": "8",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpufreq_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "localhost" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "cpufreq" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "8" }
     ]
    },
    {
     "alias": "9",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpufreq_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "localhost" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "cpufreq" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "9" }
     ]
    },
    {
     "alias": "10",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpufreq_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "localhost" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "cpufreq" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "10" }
     ]
    },
    {
     "alias": "11",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpufreq_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "localhost" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "cpufreq" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "11" }
     ]
    },
    {
     "alias": "12",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpufreq_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "localhost" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "cpufreq" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "12" }
     ]
    },
    {
     "alias": "13",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpufreq_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "localhost" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "cpufreq" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "13" }
     ]
    },
    {
     "alias": "14",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpufreq_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "localhost" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "cpufreq" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "14" }
     ]
    },
    {
     "alias": "15",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpufreq_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "localhost" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "cpufreq" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "15" }
     ]
    },
    {
     "alias": "16",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpufreq_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "localhost" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "cpufreq" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "16" }
     ]
    },
    {
     "alias": "17",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpufreq_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "localhost" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "cpufreq" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "17" }
     ]
    },
    {
     "alias": "18",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpufreq_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "localhost" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "cpufreq" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "18" }
     ]
    },
    {
     "alias": "19",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpufreq_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "localhost" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "cpufreq" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "19" }
     ]
    },
    {
     "alias": "20",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpufreq_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "localhost" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "cpufreq" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "20" }
     ]
    },
    {
     "alias": "21",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpufreq_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "localhost" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "cpufreq" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "21" }
     ]
    },
    {
     "alias": "22",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpufreq_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "localhost" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "cpufreq" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "22" }
     ]
    },
    {
     "alias": "23",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpufreq_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "localhost" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "cpufreq" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "23" }
     ]
    },
    {
     "alias": "24",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpufreq_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "localhost" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "cpufreq" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "24" }
     ]
    },
    {
     "alias": "25",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpufreq_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "localhost" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "cpufreq" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "25" }
     ]
    },
    {
     "alias": "26",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpufreq_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "localhost" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "cpufreq" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "26" }
     ]
    },
    {
     "alias": "27",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpufreq_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "localhost" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "cpufreq" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "27" }
     ]
    },
    {
     "alias": "28",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpufreq_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "localhost" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "cpufreq" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "28" }
     ]
    },
    {
     "alias": "29",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpufreq_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "localhost" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "cpufreq" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "29" }
     ]
    },
    {
     "alias": "30",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpufreq_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "localhost" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "cpufreq" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "30" }
     ]
    },
    {
     "alias": "31",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpufreq_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "localhost" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "cpufreq" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "31" }
     ]
    },
    {
     "alias": "32",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpufreq_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "localhost" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "cpufreq" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "32" }
     ]
    },
    {
     "alias": "33",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpufreq_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "localhost" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "cpufreq" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "33" }
     ]
    },
    {
     "alias": "34",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpufreq_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "localhost" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "cpufreq" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "34" }
     ]
    },
    {
     "alias": "35",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpufreq_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "localhost" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "cpufreq" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "35" }
     ]
    },
    {
     "alias": "36",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpufreq_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "localhost" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "cpufreq" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "36" }
     ]
    },
    {
     "alias": "37",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpufreq_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "localhost" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "cpufreq" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "37" }
     ]
    },
    {
     "alias": "38",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpufreq_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "localhost" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "cpufreq" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "38" }
     ]
    },
    {
     "alias": "39",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpufreq_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "localhost" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "cpufreq" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "39" }
     ]
    }
   ]
  },
  {
   "title": "$CPU_1 and $CPU_2 Frequency",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "alias": "$CPU_1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpufreq_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "localhost" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "cpufreq" },
      { "condition": "AND", "key": "type_instance", "operator": "=~", "value": "/^$CPU_1$/" }
     ]
    },
    {
     "alias": "$CPU_2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpufreq_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "localhost" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "cpufreq" },
      { "condition": "AND", "key": "type_instance", "operator": "=~", "value": "/^$CPU_2$/" }
     ]
    }
   ]
  }
 ]
}