{
 "title": "System Summary",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 10, "x": 0, "y": 0 },
   "content": "<h1 align = \"center\">Upstream</h1>"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 10, "x": 10, "y": 0 },
   "content": "<h1 align = \"center\">Downstream</h1>"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 0 },
   "content": "<h1 align = \"center\">Configuration</h1>"
  },
  {
   "title": "Total Upstream Throughput",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 2 },
   "format": "Gbits",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"last\") / 1000000000\nFROM\n(\nSELECT last(\"value\") \nFROM \"autogen\".\"upstream_tx\" \nWHERE ( \"type\" = 'bits_per_second')\nGROUP BY host\n)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Upstream Total Packets",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 6, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "downstream_rx",
     "query": "SELECT sum(\"last\") / 1000\nFROM\n(\nSELECT last(\"value\") \nFROM \"autogen\".\"upstream_tx\" \nWHERE ( \"type\" = 'packets_per_second')\nGROUP BY host\n)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "select tag value" }
     ]
    }
   ]
  },
  {
   "title": "Total Downstream Throughput",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 6, "x": 10, "y": 2 },
   "format": "Gbits",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"last\") / 1000000000\nFROM\n(\nSELECT last(\"value\") \nFROM \"autogen\".\"downstream_rx\" \nWHERE ( \"type\" = 'bits_per_second')\nGROUP BY host\n)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Downstream Total Packets",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "downstream_rx",
     "query": "SELECT sum(\"last\") / 1000\nFROM\n(\nSELECT last(\"value\") \nFROM \"autogen\".\"downstream_rx\" \nWHERE ( \"type\" = 'packets_per_second')\nGROUP BY host\n)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "select tag value" }
     ]
    }
   ]
  },
  {
   "title": "Number of Service Groups",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"last\") \nFROM\n(\nSELECT last(\"value\") \nFROM \"autogen\".\"downstream_rx\" \nWHERE ( \"type\" = 'packets_per_second')\nGROUP BY host\n)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "select tag value" }
     ]
    }
   ]
  },
  {
   "title": "Upstream Avg Packet Size",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_tx",
     "query": "SELECT last(\"value\") FROM \"downstream_rx\" WHERE (\"type\" = 'average_frame_size_per_second') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "average_frame_size_per_second" }
     ]
    }
   ]
  },
  {
   "title": "Dowstream Avg Packet Size",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "downstream_rx",
     "query": "SELECT last(\"value\") FROM \"downstream_rx\" WHERE (\"type\" = 'average_frame_size_per_second') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "average_frame_size_per_second" }
     ]
    }
   ]
  },
  {
   "title": "Downstream Rx Dropped",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "downstream_rx",
     "query": "SELECT sum(\"last\") /1000\nFROM\n(\nSELECT last(\"value\") \nFROM \"autogen\".\"downstream_rx\" \nWHERE ( \"type\" = 'dropped_per_second')\nGROUP BY host\n)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "/1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "dropped_per_second" }
     ]
    }
   ]
  },
  {
   "title": "Total Active Subscribers",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "downstream_value",
     "query": "\nSELECT sum(\"last\") \nFROM\n(\nSELECT last(\"value\") \nFROM \"autogen\".\"downstream_value\" \nWHERE ( \"type\" = 'active_cms_per_second')\nGROUP BY host\n)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "service_group_10" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "active_cms_per_second" }
     ]
    }
   ]
  },
  {
   "title": "Upstream Dropped",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "downstream_rx",
     "query": "SELECT sum(\"last\") /1000\nFROM\n(\nSELECT last(\"value\") \nFROM \"autogen\".\"upstream_rx\" \nWHERE ( \"type\" = 'dropped_per_second')\nGROUP BY host\n)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "/1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "dropped_per_second" }
     ]
    }
   ]
  },
  {
   "title": "Scheduler Dropped",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "downstream_rx",
     "query": "SELECT sum(\"last\") /1000\nFROM\n(\nSELECT last(\"value\") \nFROM \"autogen\".\"downstream_value\" \nWHERE ( \"type\" = 'sched_dropped_per_second')\nGROUP BY host\n)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "/1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "dropped_per_second" }
     ]
    }
   ]
  },
  {
   "title": "Wall Power",
   "type": "graph",
   "gridPos": { "h": 11, "w": 10, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "alias": "Watts",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "ipmi_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      {
       "key": "type_instance",
       "operator": "=",
       "value": "PS1 Input Power power_supply (10.1)"
      },
      { "condition": "AND", "key": "type", "operator": "=", "value": "power" }
     ]
    }
   ]
  },
  {
   "title": "CPU Socket Power Consumption",
   "type": "graph",
   "gridPos": { "h": 11, "w": 7, "x": 10, "y": 10 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "alias": "Watts - Pkg 0",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "turbostat_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "pkg00" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "power" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "pkg" }
     ]
    },
    {
     "alias": "Watts - Pkg 1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "turbostat_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "pkg01" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "power" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "pkg" }
     ]
    }
   ]
  },
  {
   "title": "Memory Bandwidth",
   "type": "graph",
   "gridPos": { "h": 11, "w": 7, "x": 17, "y": 10 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "intel_rdt_value",
     "query": "\nSELECT sum(\"last\") / 1000000\nFROM\n(\n\nSELECT last(\"value\") FROM \"intel_rdt_value\" WHERE (\"host\" = 'localhost' AND \"type\" = 'memory_bandwidth' AND \"type_instance\" = 'local')\nGROUP BY instance\n)\nGROUP BY time(10s) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "localhost" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "memory_bandwidth" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "local" }
     ]
    }
   ]
  },
  {
   "title": "Upstream Throughput Per Service Group",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short", "label": "Bitrate (Gbps)" }
   ],
   "targets": [
    {
     "alias": "0",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_tx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "/1000000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "service_group_0" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "bits_per_second" }
     ]
    },
    {
     "alias": "1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_tx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "/1000000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "service_group_1" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "bits_per_second" }
     ]
    },
    {
     "alias": "2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_tx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "/1000000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "service_group_2" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "bits_per_second" }
     ]
    },
    {
     "alias": "3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_tx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "/1000000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "service_group_3" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "bits_per_second" }
     ]
    },
    {
     "alias": "4",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_tx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "/1000000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "service_group_4" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "bits_per_second" }
     ]
    },
    {
     "alias": "5",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_tx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "/1000000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "service_group_5" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "bits_per_second" }
     ]
    },
    {
     "alias": "6",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_tx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "/1000000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "service_group_6" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "bits_per_second" }
     ]
    },
    {
     "alias": "7",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_tx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "/1000000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "service_group_7" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "bits_per_second" }
     ]
    },
    {
     "alias": "8",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_tx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "/1000000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "service_group_8" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "bits_per_second" }
     ]
    },
    {
     "alias": "9",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_tx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "/1000000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "service_group_9" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "bits_per_second" }
     ]
    },
    {
     "alias": "10",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_tx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "/1000000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "service_group_10" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "bits_per_second" }
     ]
    },
    {
     "alias": "11",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_tx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "/1000000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "service_group_11" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "bits_per_second" }
     ]
    },
    {
     "alias": "12",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_tx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "/1000000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "service_group_12" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "bits_per_second" }
     ]
    },
    {
     "alias": "13",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_tx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "/1000000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "service_group_13" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "bits_per_second" }
     ]
    },
    {
     "alias": "14",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_tx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "/1000000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "service_group_14" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "bits_per_second" }
     ]
    },
    {
     "alias": "15",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_tx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "/1000000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "service_group_15" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "bits_per_second" }
     ]
    },
    {
     "alias": "16",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_tx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "/1000000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "service_group_16" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "bits_per_second" }
     ]
    },
    {
     "alias": "17",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_tx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "/1000000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "service_group_17" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "bits_per_second" }
     ]
    },
    {
     "alias": "18",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_tx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "/1000000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "service_group_18" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "bits_per_second" }
     ]
    },
    {
     "alias": "19",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_tx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "/1000000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "service_group_19" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "bits_per_second" }
     ]
    },
    {
     "alias": "20",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_tx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "/1000000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "service_group_20" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "bits_per_second" }
     ]
    },
    {
     "alias": "21",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_tx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "/1000000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "service_group_21" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "bits_per_second" }
     ]
    },
    {
     "alias": "22",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_tx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "/1000000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "service_group_22" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "bits_per_second" }
     ]
    },
    {
     "alias": "23",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_tx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "/1000000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "service_group_23" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "bits_per_second" }
     ]
    },
    {
     "alias": "24",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_tx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "/1000000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "service_group_24" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "bits_per_second" }
     ]
    },
    {
     "alias": "25",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_tx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "/1000000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "service_group_25" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "bits_per_second" }
     ]
    },
    {
     "alias": "26",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_tx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "/1000000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "service_group_26" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "bits_per_second" }
     ]
    },
    {
     "alias": "27",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_tx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "/1000000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "service_group_27" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "bits_per_second" }
     ]
    },
    {
     "alias": "28",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_tx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "/1000000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "service_group_28" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "bits_per_second" }
     ]
    },
    {
     "alias": "29",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_tx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "/1000000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "service_group_29" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "bits_per_second" }
     ]
    },
    {
     "alias": "30",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_tx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "/1000000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "service_group_30" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "bits_per_second" }
     ]
    },
    {
     "alias": "31",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upstream_tx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "/1000000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "service_group_31" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "bits_per_second" }
     ]
    }
   ]
  },
  {
   "title": "Downstream Throughput Per Service Group",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short", "label": "Bitrate (Gbps)" }
   ],
   "targets": [
    {
     "alias": "0",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "downstream_rx",
     "query": "SELECT distinct(\"value\") /1000000000 FROM \"downstream_rx\" WHERE (\"host\" = 'service_group_0' AND \"type\" = 'bits_per_second') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "/1000000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "service_group_0" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "bits_per_second" }
     ]
    },
    {
     "alias": "1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "downstream_rx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "/1000000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "service_group_1" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "bits_per_second" }
     ]
    },
    {
     "alias": "2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "downstream_rx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "/1000000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "service_group_2" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "bits_per_second" }
     ]
    },
    {
     "alias": "3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "downstream_rx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "/1000000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "service_group_3" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "bits_per_second" }
     ]
    },
    {
     "alias": "4",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "downstream_rx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "/1000000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "service_group_4" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "bits_per_second" }
     ]
    },
    {
     "alias": "5",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "downstream_rx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "/1000000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "service_group_5" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "bits_per_second" }
     ]
    },
    {
     "alias": "6",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "downstream_rx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "/1000000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "service_group_6" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "bits_per_second" }
     ]
    },
    {
     "alias": "7",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "downstream_rx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "/1000000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "service_group_7" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "bits_per_second" }
     ]
    },
    {
     "alias": "8",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "downstream_rx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "/1000000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "service_group_8" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "bits_per_second" }
     ]
    },
    {
     "alias": "9",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "downstream_rx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "/1000000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "service_group_9" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "bits_per_second" }
     ]
    },
    {
     "alias": "10",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "downstream_rx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "/1000000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "service_group_10" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "bits_per_second" }
     ]
    },
    {
     "alias": "11",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "downstream_rx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "/1000000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "service_group_11" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "bits_per_second" }
     ]
    },
    {
     "alias": "12",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "downstream_rx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "/1000000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "service_group_12" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "bits_per_second" }
     ]
    },
    {
     "alias": "13",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "downstream_rx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "/1000000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "service_group_13" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "bits_per_second" }
     ]
    },
    {
     "alias": "14",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "downstream_rx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "/1000000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "service_group_14" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "bits_per_second" }
     ]
    },
    {
     "alias": "15",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "downstream_rx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "/1000000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "service_group_15" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "bits_per_second" }
     ]
    },
    {
     "alias": "16",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "downstream_rx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "/1000000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "service_group_16" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "bits_per_second" }
     ]
    },
    {
     "alias": "17",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "downstream_rx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "/1000000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "service_group_17" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "bits_per_second" }
     ]
    },
    {
     "alias": "18",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "downstream_rx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "/1000000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "service_group_18" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "bits_per_second" }
     ]
    },
    {
     "alias": "19",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "downstream_rx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "/1000000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "service_group_19" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "bits_per_second" }
     ]
    },
    {
     "alias": "20",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "downstream_rx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "/1000000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "service_group_20" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "bits_per_second" }
     ]
    },
    {
     "alias": "21",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "downstream_rx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "/1000000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "service_group_21" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "bits_per_second" }
     ]
    },
    {
     "alias": "22",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "downstream_rx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "/1000000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "service_group_22" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "bits_per_second" }
     ]
    },
    {
     "alias": "23",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "downstream_rx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "/1000000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "service_group_23" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "bits_per_second" }
     ]
    },
    {
     "alias": "24",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "downstream_rx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "/1000000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "service_group_24" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "bits_per_second" }
     ]
    },
    {
     "alias": "25",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "downstream_rx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "/1000000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "service_group_25" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "bits_per_second" }
     ]
    },
    {
     "alias": "26",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "downstream_rx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "/1000000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "service_group_26" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "bits_per_second" }
     ]
    },
    {
     "alias": "27",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "downstream_rx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "/1000000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "service_group_27" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "bits_per_second" }
     ]
    },
    {
     "alias": "28",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "downstream_rx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "/1000000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "service_group_28" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "bits_per_second" }
     ]
    },
    {
     "alias": "29",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "downstream_rx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "/1000000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "service_group_29" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "bits_per_second" }
     ]
    },
    {
     "alias": "30",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "downstream_rx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "/1000000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "service_group_30" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "bits_per_second" }
     ]
    },
    {
     "alias": "31",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "downstream_rx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "/1000000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "service_group_31" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "bits_per_second" }
     ]
    }
   ]
  }
 ]
}