---
##############################################################################
# Copyright (c) 2017 Huawei Technologies Co.,Ltd and others.
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

- name: remove vcpu pin set
  lineinfile:
    dest: /etc/nova/nova.conf
    state: absent
    regexp: 'vcpu_pin_set'

- name: remove memory reserved for host
  lineinfile:
    dest: /etc/nova/nova.conf
    state: absent
    regexp: 'reserved_host_memory_mb'
