From: Ross Brattain <ross.b.brattain@intel.com>
Date: Mon, 12 Feb 2018 17:18:02 -0800
Subject: [PATCH] Update Dockerfile to add DEBIAN_FRONTEND=noninteractive

Change-Id: I7b0c7167ec38202771d3d91de3888b03c57f3b28
Signed-off-by: Ross Brattain <ross.b.brattain@intel.com>
---
 docker/Dockerfile | 14 +++++++-------
 1 file changed, 7 insertions(+), 7 deletions(-)

diff --git a/docker/Dockerfile b/docker/Dockerfile
index 0a23edbe..407b3077 100644
--- a/docker/Dockerfile
+++ b/docker/Dockerfile
@@ -1,5 +1,5 @@
 ##############################################################################
-# Copyright (c) 2015 Ericsson AB and others.
+# Copyright (c) 2017 Enea AB and others.
 #
 # All rights reserved. This program and the accompanying materials
 # are made available under the terms of the Apache License, Version 2.0
@@ -7,9 +7,9 @@
 # http://www.apache.org/licenses/LICENSE-2.0
 ##############################################################################

-FROM ubuntu:16.04
+FROM arm64v8/ubuntu:16.04

-LABEL image=opnfv/yardstick
+LABEL image=opnfv/yardstick_aarch64

 ARG BRANCH=master

@@ -24,8 +24,8 @@ ENV YARDSTICK_REPO_DIR="${REPOS_DIR}/yardstick" \
     RELENG_REPO_DIR="${REPOS_DIR}/releng" \
     STORPERF_REPO_DIR="${REPOS_DIR}/storperf"

-# noninteractive will prevent questions from being asked during the install
-RUN apt-get update && env DEBIAN_FRONTEND=noninteractive apt-get install -y git python-setuptools python-pip && apt-get -y autoremove && apt-get clean
+RUN apt-get update && env DEBIAN_FRONTEND=noninteractive apt-get install -y git python-setuptools python-pip && apt-get -y autoremove && \
+    apt-get install -y libssl-dev && apt-get -y install libffi-dev && apt-get clean
 RUN easy_install -U setuptools==30.0.0
 RUN pip install appdirs==1.4.0 pyopenssl==17.5.0 python-openstackclient==3.11.0

@@ -44,8 +44,8 @@ RUN echo "daemon off;" >> /etc/nginx/nginx.conf

 EXPOSE 5000

-ADD http://download.cirros-cloud.net/0.3.5/cirros-0.3.5-x86_64-disk.img ${IMAGE_DIR}
-ADD http://cloud-images.ubuntu.com/xenial/current/xenial-server-cloudimg-amd64-disk1.img ${IMAGE_DIR}
+ADD http://download.cirros-cloud.net/daily/20161201/cirros-d161201-aarch64-disk.img ${IMAGE_DIR}
+ADD http://cloud-images.ubuntu.com/xenial/current/xenial-server-cloudimg-arm64-disk1.img ${IMAGE_DIR}

 COPY ./exec_tests.sh /usr/local/bin/

