From: Cristina Pauna <cristina.pauna@enea.com>
Date: Thu, 11 Jan 2018 19:06:26 +0200
Subject: [PATCH] Patch for Yardstick AARCH64 Docker file

Signed-off-by: Cristina Pauna <cristina.pauna@enea.com>
Signed-off-by: Alexandru Nemes <alexandru.nemes@enea.com>
---
 docker/Dockerfile | 13 +++++++------
 1 file changed, 7 insertions(+), 6 deletions(-)

diff --git a/docker/Dockerfile b/docker/Dockerfile
index 2ee5b4c..23e5ea5 100644
--- a/docker/Dockerfile
+++ b/docker/Dockerfile
@@ -1,5 +1,5 @@
 ##############################################################################
-# Copyright (c) 2015 Ericsson AB and others.
+# Copyright (c) 2017 Enea AB and others.
 #
 # All rights reserved. This program and the accompanying materials
 # are made available under the terms of the Apache License, Version 2.0
@@ -7,9 +7,9 @@
 # http://www.apache.org/licenses/LICENSE-2.0
 ##############################################################################

-FROM ubuntu:16.04
+FROM arm64v8/ubuntu:16.04

-LABEL image=opnfv/yardstick
+LABEL image=opnfv/yardstick_aarch64

 ARG BRANCH=master

@@ -24,7 +24,8 @@ ENV YARDSTICK_REPO_DIR="${REPOS_DIR}/yardstick" \
     RELENG_REPO_DIR="${REPOS_DIR}/releng" \
     STORPERF_REPO_DIR="${REPOS_DIR}/storperf"

-RUN apt-get update && apt-get install -y git python-setuptools python-pip && apt-get -y autoremove && apt-get clean
+RUN apt-get update && apt-get install -y git python-setuptools python-pip && apt-get -y autoremove && \
+    apt-get install -y libssl-dev && apt-get -y install libffi-dev && apt-get clean
 RUN easy_install -U setuptools==30.0.0
 RUN pip install appdirs==1.4.0 pyopenssl==17.5.0 python-openstackclient==3.11.0 python-heatclient==1.11.0

@@ -43,8 +44,8 @@ RUN echo "daemon off;" >> /etc/nginx/nginx.conf

 EXPOSE 5000

-ADD http://download.cirros-cloud.net/0.3.5/cirros-0.3.5-x86_64-disk.img ${IMAGE_DIR}
-ADD http://cloud-images.ubuntu.com/xenial/current/xenial-server-cloudimg-amd64-disk1.img ${IMAGE_DIR}
+ADD http://download.cirros-cloud.net/daily/20161201/cirros-d161201-aarch64-disk.img ${IMAGE_DIR}
+ADD http://cloud-images.ubuntu.com/xenial/current/xenial-server-cloudimg-arm64-disk1.img ${IMAGE_DIR}

 COPY ./exec_tests.sh /usr/local/bin/

