---
##############################################################################
# Copyright (c) 2017 Huawei Technologies Co.,Ltd and others.
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

- name: restart "{{ service }}" service
  service:
    name: "{{ service }}"
    state: restarted
  become: true
  when: ansible_os_family == "Debian"

- name: restart "openstack-{{ service }}" service
  service:
    name: "openstack-{{ service }}"
    state: restarted
  become: true
  when: ansible_os_family == "RedHat"
