# yardstick service pod
---
apiVersion: v1
kind: Pod
metadata:
  name: yardstick-pod
  labels:
    app: yardstick-pod
spec:
  containers:
  - name: yardstick
    image: opnfv/yardstick:latest
    ports:
    - containerPort: 5000
    volumeMounts:
    - name: docker-sock
      mountPath: /var/run/docker.sock
    - name: yardstick-configmap-volume
      mountPath: /etc/yardstick/yardstick.conf
      subPath: yardstick.conf
  - name: influxdb
    image: influxdb:1.6.0-alpine
    ports:
    - containerPort: 8086
    command:
    - /bin/entrypoint.sh
    volumeMounts:
    - name: influxdb-configmap-volume
      mountPath: /bin/entrypoint.sh
      readOnly: true
      subPath: entrypoint.sh
  - name: grafana
    image: opnfv/yardstick:yardstick-grafana
    ports:
    - containerPort: 3000
  volumes:
  - name: docker-sock
    hostPath:
      # directory location on host
      path: /var/run/docker.sock
      # this field is optional
      # type: Directory
  - name: yardstick-configmap-volume
    configMap:
      name: yardstick-configmap
  - name: influxdb-configmap-volume
    configMap:
      defaultMode: 0700
      name: influxdb-configmap

# configmap of yardstick
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: yardstick-configmap
  namespace: default
data:
  yardstick.conf: |-
    [DEFAULT]
    debug = False
    dispatcher = influxdb

    [dispatcher_http]
    timeout = 5
    target = http://127.0.0.1:8000/results

    [dispatcher_file]
    file_path = /tmp/yardstick.out
    max_bytes = 0
    backup_count = 0

    [dispatcher_influxdb]
    timeout = 5
    target = http://localhost:8086
    db_name = yardstick
    username = root
    password = root

    [nsb]
    trex_path = /opt/nsb_bin/trex/scripts
    bin_path = /opt/nsb_bin
    trex_client_lib = /opt/nsb_bin/trex_client/stl

# configmap of influxdb
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: influxdb-configmap
data:
  entrypoint.sh: |-
    #!/bin/bash
    /entrypoint.sh influxd
    influx -host 127.0.0.1 -port 8086 -execute \
    "CREATE USER \"root\" WITH PASSWORD 'root' WITH ALL PRIVILEGES"
    influx -host 127.0.0.1 -port 8086 -execute \
    "CREATE DATABASE \"yardstick\""

# service exposing yardstick gui and grafana
---
apiVersion: v1
kind: Service
metadata:
  name: yardstick-service
spec:
    ports:
    - port: 5000
      targetPort: 5000
      name: yardstick-gui-port
    - port: 3000
      targetPort: 3000
      name: yardstick-grafana-port
    selector:
      app: yardstick-pod
    type: NodePort
