# Copyright (c) 2017 Intel Corporation.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
- name: Update repositories
  apt:
    update_cache: yes

- name: Install core packages
  action: "{{ ansible_pkg_mgr }} name={{ item }} state=present"
  with_items:
    - wget
    - curl
    - screen
    - procps
    - socat
    - sshpass
    - sudo
    - vim
    - libffi-dev
    - libfuse-dev
    - libssl-dev
    - libxft-dev
    - libxml2-dev
    - libxss-dev
    - libxslt1-dev
    - libzmq3-dev
    - qemu-user-static
    - qemu-utils
    - kpartx
    - python
    - python-setuptools
    - python-dev
    - python-libvirt
    - python-virtualenv
    - bridge-utils
    - ebtables
    - openssl
    - ccze
    - nginx-full
    - uwsgi
    - uwsgi-plugin-python
    - supervisor
    - lsof
    - nodejs
    - npm
    - rabbitmq-server

- name: Install libc6:arm64 package
  action: "{{ ansible_pkg_mgr }} name={{ item }} state=present"
  with_items:
    - libc6:arm64
  when:
    - arch is defined
    - arch != arch_arm64
    - installation_mode == inst_mode_container

- name: Remove dependencies that are no longer required
  apt:
    update_cache: yes

- name: Remove useless packages from the cache
  apt:
    autoclean: yes

# There is a bug with the easy install ansible module in Ubuntu 16.04 linux.
# Refer https://github.com/ansible/ansible/issues/23534
- name: Install pip
  shell: easy_install -U pip
  when:
    - ansible_distribution == 'Ubuntu'
    - ansible_distribution_major_version|int <= 16

- name: Install python-pip
  action: "{{ ansible_pkg_mgr }} name=python-pip state=present"
  when:
    - ansible_distribution == 'Ubuntu'
    - ansible_distribution_major_version|int >= 17

- name: Install required docker-py module
  pip:
    name: docker-py
    state: latest
  environment: "{{ proxy_env }}"
