# Copyright (c) 2018 Intel Corporation.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
- name: Define variables
  set_fact:
    gui_dir: "{{ yardstick_dir }}/gui/"

- name: Run gui.sh
  shell:
    cmd: /bin/bash gui.sh
    chdir: "{{ gui_dir }}"

- name: Create nginx/yardstick directory
  file:
    path: /etc/nginx/yardstick
    state: directory
    recurse: yes

- name: Move dist to /etc/nginx/yardstick/gui
  shell:
    cmd: mv dist /etc/nginx/yardstick/gui
    chdir: "{{ gui_dir }}"
