from django.conf.urls import url
from . import views
app_name = 'execute_test'
urlpatterns = [
    url(r'^traffic-generator$', views.index, name='index'),
    url(r'^logging$', views.initiate_logging, name='logging'),
    url(r'^results$', views.show_results, name='results'),
    url(r'^result$', views.show_tc_result, name='tc-result'),
    url(r'^(?P<tg_type>[a-z]+)/vnf-types$',
        views.get_vnf_list, name='vnf-types'),
    url(r'^(?P<vnf_type>[a-z]+)/deployment-types$',
        views.get_deployment_list, name='deployment-types'),
    url(r'^(?P<deployment_type>[a-z]+)/test-types$',
        views.get_test_list, name='test-types'),
#    url(r'^(?P<test_type>[a-z_]+)/ip-versions$',
#        views.get_ipversion_list, name='ip-versions'),
#    url(r'^(?P<ip_type>[a-z0-9]+)/packet-types',
#        views.get_packsize_list, name='pack-types'),
#    url(r'^(?P<packet_type>[a-z0-9]+)/vnf-config',
#        views.vnf_config, name='vnf-config'),
    url(r'^test-case/(?P<test_id>[0-9]+)',
        views.select_test_case, name='select-test-case'),
    url(r'^test-cases', views.get_test_case_list, name='list-test-case'),
    url(r'^config/vnf$', views.config_vnf, name='config-vnf'),
    url(r'^test_case_execution$',
        views.execute_test_case, name='execute-test-case'),
    url(r'^regression$', views.execute_regression, name='execute-regression'),
    url(r'^regression/(?P<deployment_type>[a-z]+)/regression-type',
        views.regression_type,  name='regression-types'),
    url(r'^regression/(?P<regression_type>[a-z_]+)/ip-version',
        views.regression_ip_version,  name='regression-ip-versions'),
    url(r'^regression/(?P<vnf_type>[a-z]+)/deployment-type',
        views.regression_deployment_type,  name='regression-deployment-types'),
    url(r'^regression/(?P<ip_version>[a-z0-9]+)/vnf-configuration',
        views.regression_config_vnf,  name='regression-vnf-configuration'),
    url(r'^regression/regression-mode',
        views.regression_mode,  name='regression-mode'),
    url(r'^regression/priority/$',
        views.regression_priority, name='regression-priority'),
    url(r'^regression/priority/(?P<priority>[0-3])$',
        views.execute_regression_priority, name='execute-priority'),
    url(r'^regression/testsuite',
        views.regression_testsuite, name='regression-testsuit'),
    url(r'^regression/results',
        views.regression_results, name='regression-results'),
    url(r'^scaleup$', views.execute_scaleup, name='execute-scaleup'),
    url(r'^scaleup/results$', views.scaleup_results, name='scaleup-results'),
]
