# Copyright (c) 2017 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
- name: vFW_vnf make clean
  my_make: chdir="{{ vfw_build_dir }}" target=clean extra_args="-j {{ ansible_processor_vcpus }}"
  environment:
    RTE_SDK: "{{ RTE_SDK }}"
    RTE_TARGET: "{{ RTE_TARGET }}"
    VNF_CORE: "{{ samplevnf_path }}"

#- name: make vFW VNF
#  my_make: chdir="{{ vfw_build_dir }}" extra_args="-j {{ ansible_processor_vcpus }}"
#  environment:
#    RTE_SDK: "{{ RTE_SDK }}"
#    RTE_TARGET: "{{ RTE_TARGET }}"
#    VNF_CORE: "{{ samplevnf_path }}"

- name: make vFW VNF
  command: make chdir="{{ vfw_build_dir }}" extra_args="-j {{ ansible_processor_vcpus }}" all
  args:
    chdir: "{{ vfw_build_dir }}"
  environment:
    RTE_SDK: "{{ RTE_SDK }}"
    RTE_TARGET: "{{ RTE_TARGET }}"
    VNF_CORE: "{{ samplevnf_path }}"

#- command: cp "{{ vfw_build_dir }}/vFW/build/ip_pipeline" "{{ INSTALL_BIN_PATH }}/vFW_vnf"
- name: Install vFW VNF
  copy:
    src: "{{ vfw_build_dir }}/build/vFW"
    dest: "{{ INSTALL_BIN_PATH }}/vFW"
    remote_src: True
    # make executable
    mode: 0755

#- command: cp "{{ vfw_build_dir }}/vFW/config/full_tm_profile_10G.cfg" "{{ INSTALL_BIN_PATH }}/"
#- copy:
#    src: "{{ vfw_build_dir }}/vFW/config/full_tm_profile_10G.cfg"
#    dest: "{{ INSTALL_BIN_PATH }}/"
