##############################################################################
# Copyright (c) 2017 user@TRAFCLASS-PACKET1.fuel.local and others.
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################
heat_template_version: 2014-10-16
description: HOT template to create a DPI

parameters:
   name:
      type: string
      default: cpu_stress
   cores:
       type: string
   memory:
       type: string
   network:
       type: string
   subnet:
       type: string

resources:
   port:
      type: OS::Neutron::Port
      properties:
         network: { get_param: network }
         port_security_enabled: false
         fixed_ips:
            - subnet: { get_param: subnet }

   vm1:
      type: OS::Nova::Server
      properties:
         name: traffic_vm1
         image: ubuntu1404
         user_data:
            str_replace:
               template: |
                  #!/bin/sh
                  echo "Creating custom user..."
                  useradd clouduser -g admin -s /bin/bash -m
                  echo clouduser:secrete | chpasswd
                  echo "Enabling ssh password login..."
                  sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
                  service ssh restart
                  sleep 1

                  ifconfig eth1 up
                  dhclient eth1

                  sed -i 's/localhost/localhost traffic_vm1/g' /etc/hosts
                  touch /etc/resolvconf/resolv.conf.d/tail
                  echo 'nameserver 10.118.32.193' > /etc/resolvconf/resolv.conf.d/tail
                  resolvconf -u
                  echo 'nameserver 10.118.32.193' > /etc/resolv.conf


                  # Installation of stress
                  apt-get install -y stress

                  cd /home/clouduser

                  # workload setup
                  echo 'stress -c $CORES --vm-bytes $MEMORY' > ./stress.sh
                  chmod +x ./stress.sh
                  nohup ./stress.sh &
                  #nohup stress -c #CORES --vm-bytes #MEMORY

               params:
                  $NAME: { get_param: name }
                  $CORES: { get_param: cores }
                  $MEMORY: { get_param: memory }

         flavor: m1.small
         networks:
            - port: { get_resource: port }
