- name: Check requirements
  hosts: civirthost

  vars:
    vcpu_t: 0
    vram_t: 0
    disk_t: 0

  tasks:
  - name: Include
    include_vars:
      file: file1
      name: file1_vars

  - name: Store total CPU, RAM, Disk requested resources
    set_fact:
      vcpu_t: "{{item.vcpus|int + vcpu_t|int}}"
      vram_t: "{{item.ram|int + vram_t|int}}"
      disk_t: "{{item.disk|int + disk_t|int}}"
    with_items: "{{file1_vars.nodes}}"

  - name: Fail if not enough RAM
    fail: msg="Failed not enough RAM"
    when: ansible_memory_mb.nocache.free < vram_t|int

  - name: Fail if not enough CPU
    fail: msg="Failed not enough CPU"
    when: ansible_processor_vcpus < vcpu_t|int

  - name: Get available disk space
    shell: df -BM / | tail -1 | awk '{print substr($4, 1, length($4)-1)}'
    register: disk_avail

  - name: Fail if not enough disk space
    fail: msg="Failed not enough disk space"
    when: disk_avail.stdout|int < disk_t|int

    # Also possible to use ansible_all_ipv4_addresses variable from facts
  - name: debug print all interface ipv4 data
    set_fact:
      ipv4_addr: "{% set ipv4_addr = ipv4_addr|default([]) + [hostvars[inventory_hostname]['ansible_' + item]['ipv4']['address']] %}{{ ipv4_addr|list }}"
    when: "'ipv4' in hostvars[inventory_hostname]['ansible_'~item]"
    with_items:
       "{{ ansible_interfaces | map('replace', '-','_') | list }}"
