---
##############################################################################
# Copyright (c) 2017 Huawei Technologies Co.,Ltd and others.
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

- hosts: localhost
  roles:
    - migrate_local_setup

- hosts: nodes
  roles:
    - backup_nova_conf
    - { role: set_nova_conf, section: "DEFAULT", key: "live_migration_flag", value: "VIR_MIGRATE_UNDEFINE_SOURCE,VIR_MIGRATE_PEER2PEER,VIR_MIGRATE_LIVE,VIR_MIGRATE_TUNNELLED" }
    - { role: set_nova_conf, section: "DEFAULT", key: "vncserver_listen", value: "0.0.0.0" }
    - { role: set_nova_conf, section: "DEFAULT", key: "scheduler_default_filters", value: "NUMATopologyFilter,AggregateInstanceExtraSpecsFiler" }

- hosts: controller
  roles:
    - { role: restart_nova_service, service: "nova-scheduler" }
    - { role: restart_nova_service, service: "nova-api" }
    - { role: restart_nova_service, service: "nova-conductor" }

- hosts: compute
  roles:
      - { role: restart_nova_service, service: "nova-compute" }
