---
##############################################################################
# Copyright (c) 2017 Huawei Technologies Co.,Ltd and others.
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

- name: add scheduler_default_filters for cpu pinning
  lineinfile:
    dest: /etc/nova/nova.conf
    insertafter: 'DEFAULT'
    line: 'scheduler_default_filters={{cpu_pin_filters}}'
