# Copyright (c) 2016-2017 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
  # must do this before setting yum proxy
  - name: find yum/dnf config
    stat: "path={{ item }}"
    register: packager_conf_stat
    with_items:
      - /etc/yum.conf
      - /etc/dnf/dnf.conf

  - name: insert yum/dnf proxy(http)
    # insert after [main] section
    lineinfile:
      dest: "{{ item.stat.path }}"
      state: present
      regexp: "^proxy\\s*=\\s*{{ calc_proxy_env.http_proxy }}"
      insertafter: "^\\[main\\]"
      line: "proxy={{ calc_proxy_env.http_proxy }}"
    when: '"http_proxy" in calc_proxy_env and item.stat.isreg is defined and item.stat.isreg'
    with_items: "{{ packager_conf_stat.results }}"

  - name: verify proxy
    command: "grep proxy= {{ item.stat.path }}"
    when: 'item.stat.isreg is defined and item.stat.isreg'
    with_items: "{{ packager_conf_stat.results }}"
    register: yum_proxy_lines

  - name: yum disable fastest mirrors
    include: yum_disable_fastestmirrors.yml
    when: ansible_pkg_mgr == 'yum'

  - name: Test proxy connection
    # try workaround call makecache directly
    # yum module was failing for some reason
    async: "{{ connection_timeout }}"
    command: "{{ ansible_pkg_mgr }} -d2 -y makecache"
    poll: 0
    register: test_proxy_job_id
