---
  - name: yum disable fastest mirrors
    lineinfile:
      dest: "/etc/yum/pluginconf.d/fastestmirror.conf"
      regexp: "^enabled=1"
      line: "enabled=0"
    ignore_errors: true

  - name: yum clean all
    command:  yum clean all

